### ISSUE TITLE
Fix error in unlocking a locked record

### ISSUE THREAD

**Issue by Aroke-Anna8** [tracits/rodant#116]
Considering, a user unlocks a locked record, edits, completes double entry and finalizes the record(expecting it to get locked).
The tool does not lock the record.
Instead shows 'Editing Patient study ID:XXX' without allowing to make any edits.
Attached a screenshot for reference.

![2020-07-06 (8)](https://user-images.githubusercontent.com/40137381/86621196-64e9ac00-bfdb-11ea-9851-669d4b72ef2a.png)

**Comment by martingerdin** [comment]
To replicate:
1. Import any database in `data/`
2. Create a new record
3. Set complete record to 1
4. Complete double entry 
5. Click check
6. Click finalize 

The record should now be locked, display an unlock button, and show “Viewing Patient study ID”.

As Anna says however, the record shows “Editing” instead of viewing, and there’s no unlock button. It’s not editable though.

Probably an issue with how the tool handles the `locked` field.

**Comment by KarnellSchultz** [comment]
Thanks for that info. I'll check this out later today and get back to you.

**Comment by martingerdin** [comment]
Fixed by #119
